#
# .travis.yml
# ndt: n-dimensional tracer
#
# Copyright (c) 2019 Bryan Franklin. All rights reserved.
#
language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake
      - libpng-dev
      - libjpeg-dev
      - libyaml-dev
      - mpich

#before_install:
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake || brew upgrade cmake; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install jpeg || brew upgrade jpeg; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libpng || brew upgrade libpng; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libyaml || brew upgrade libyaml; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpich || brew upgrade mpich; fi
#  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

script:
- cmake .
- make
